CREATE SCHEMA IF NOT EXISTS SPORT;

SET SCHEMA SPORT;

CREATE TABLE F1_DRIVERS (ID INTEGER, NAME VARCHAR(50), SHORTNAME VARCHAR(3), CAR_NUMBER INTEGER, TEAM VARCHAR(50));

INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (1, 'VERSTAPPEN', 'VER', 33, 'RED BULL');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (2, 'PEREZ', 'PER', 11, 'RED BULL');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (3, 'LECLERC', 'LEC', 16, 'FERRARI');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (4, 'SAINZ', 'SAI', 55, 'FERRARI');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (5, 'PIASTRI', 'PIA', 81, 'MCLAREN');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (6, 'NORRIS', 'NOR', 4, 'MCLAREN');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (7, 'HAMILTON', 'HAM', 44, 'MERCEDES');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (8, 'RUSSEL', 'RUS', 63, 'MERCEDES');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (9, 'ALONSO', 'ALO', 14, 'ASTON MARTIN');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (10, 'STROLL', 'STR', 18, 'ASTON MARTIN');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (11, 'OCON', 'OCO', 31, 'ALPINE');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (12, 'GASLY', 'GAS', 10, 'ALPINE');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (13, 'RICCIARDO', 'RIC', 3, 'RACING BULLS');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (14, 'TSUNODA', 'TSU', 22, 'RACING BULLS');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (15, 'MAGNUSSEN', 'MAG', 20, 'HAAS');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (16, 'HULKENBERG', 'HUL', 27, 'HAAS');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (17, 'ALBON', 'ALB', 23, 'WILLIAMS');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (18, 'COLAPINTO', 'COL', 43, 'WILLIAMS');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (19, 'BOTTAS', 'BOT', 77, 'SAUBER');
INSERT INTO F1_DRIVERS (ID, NAME, SHORTNAME, CAR_NUMBER, TEAM) VALUES (20, 'ZOUH', 'ZOU', 24, 'SAUBER');